"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ProductSerivce_1 = require("./ProductSerivce");
var product_1 = require("./product");
var _productService = new ProductSerivce_1.ProductService();
var result;
result = _productService.getById(2);
var p = new product_1.Product();
p.id = 2;
p.name = "İphone 6";
p.price = 4000;
p.category = "Telefon";
_productService.saveProduct(p);
// _productService.deleteProduct(result);
result = _productService.getProducts();
result = _productService.getProducts();
console.log(result);
